### ISSUE TITLE
I have a question about  Storage Engine

### ISSUE THREAD

**Issue by orz--** [bizstation/transactd#37]
Hi,
Are Transactd supported only InnnoDB Storage Engine?
Or are Spider and Mroonga, etc. also supporting it?

**Comment by bizstation** [comment]
Yes. We only tests with InnoDB.

However, Transactd probably works on other storage engines, because it calls Handler interface in MySQL.

InnoDB-specific features will be checked before calling it. So, basically it will not cause an error even on other storage engines. (By the way, it works well on MyISAM.)

Please test it and tell us problems if you do not mind. We will respond if possible.

**Comment by orz--** [comment]
thank you for your quick response.
I’ll give it a try.
